spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  h2:
    console:
      enable: true
      settings:
        db_close_on_exit: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: foo
    password: bar
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/mydb
#    username: foo
#    password: bar
#    driverClassName: org.postgresql.Driver